# Generated by Django 6.0.3 on 2026-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('poblacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
